{{- if .Values.deviceconnect.enabled }}
{{- $context := (dict "dot" . "component" "deviceconnect") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mender.fullname" . }}-deviceconnect
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mender.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "mender.fullname" . }}-deviceconnect
    app.kubernetes.io/component: deviceconnect
spec:
  {{- if not (or .Values.deviceconnect.hpa .Values.default.hpa) }}
  replicas: {{ .Values.deviceconnect.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mender.fullname" . }}-deviceconnect

  # if deployment is not completed within 10 min, consider it failed,
  # as result deployment Reason=ProgressDeadlineExceeded
  # needs to be big enough to rollout to complete
  progressDeadlineSeconds: 600

  # Rollout upgrade one by one
  # In this case we warranty there are always instances online.
  # In case any issues, they will be detected early and deployment be stopped.
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    {{- include "mender.deviceconnectPodTemplate" $context | nindent 4 }}

{{- end }}
