{{- if .Values.dbmigration.enable }}
{{- $merged := merge (deepCopy .Values.dbmigration) (deepCopy (default (dict) .Values.default)) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mender.fullname" . }}-db-data-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-upgrade,pre-install
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  {{- with .Values.dbmigration.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mender.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "mender.fullname" . }}-db-data-migration
    app.kubernetes.io/component: job
spec:
  backoffLimit: {{ .Values.dbmigration.backoffLimit | default 5 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mender.fullname" . }}-db-data-migration
    spec:
      {{- with $merged.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with $merged.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- if .Values.dbmigration.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.dbmigration.podSecurityContext "enabled" | toYaml | nindent 8 }}
{{- end }}

{{- if .Values.global.s3.AWS_SERVICE_ACCOUNT_NAME }}
      serviceAccountName: {{ .Values.global.s3.AWS_SERVICE_ACCOUNT_NAME }}
{{- end }}
      restartPolicy: Never
      containers:


{{- if .Values.global.image.username }}
      imagePullSecrets:
      - name: docker-registry-prerelease
{{- else }}
{{- $ips := .Values.default.imagePullSecrets  }}
{{- if $ips }}
      imagePullSecrets:
{{ toYaml $ips | indent 6 }}
{{- end }}
{{- end }}

{{- with .Values.dbmigration.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
{{- end }}
{{- end }}
