{{- if .Values.dbmigration.enable }}
{{- $merged := merge (deepCopy .Values.dbmigration) (deepCopy (default (dict) .Values.default)) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mender.fullname" . }}-db-data-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-upgrade,pre-install
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  {{- with .Values.dbmigration.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mender.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "mender.fullname" . }}-db-data-migration
    app.kubernetes.io/component: job
spec:
  backoffLimit: {{ .Values.dbmigration.backoffLimit | default 5 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mender.fullname" . }}-db-data-migration
    spec:
      {{- with $merged.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with $merged.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- if .Values.dbmigration.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.dbmigration.podSecurityContext "enabled" | toYaml | nindent 8 }}
{{- end }}

{{- if .Values.global.s3.AWS_SERVICE_ACCOUNT_NAME }}
      serviceAccountName: {{ .Values.global.s3.AWS_SERVICE_ACCOUNT_NAME }}
{{- end }}
      restartPolicy: Never
      containers:

      - name: iot-manager-migration
{{- if .Values.global.enterprise }}
        image: {{ .Values.iot_manager.image.registry | default "registry.mender.io" }}/{{ .Values.iot_manager.image.repository | default "mendersoftware/iot-manager-enterprise" }}:{{ .Values.iot_manager.image.tag | default .Values.global.image.tag }}
{{- else }}
        image: {{ .Values.iot_manager.image.registry | default "docker.io" }}/{{ .Values.iot_manager.image.repository | default "mendersoftware/iot-manager" }}:{{ .Values.iot_manager.image.tag | default .Values.global.image.tag }}
{{- end }}
        imagePullPolicy: {{ .Values.iot_manager.image.imagePullPolicy }}
{{- if .Values.iot_manager.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.iot_manager.containerSecurityContext "enabled" | toYaml | nindent 10 }}
{{- end }}
        envFrom:
        - prefix: IOT_MANAGER_
          secretRef:
            name: mongodb-common-prerelease
        resources:
{{ toYaml .Values.iot_manager.resources | indent 10 }}
        args: ["migrate"]


{{- if .Values.global.image.username }}
      imagePullSecrets:
      - name: docker-registry-prerelease
{{- else }}
{{- $ips := .Values.default.imagePullSecrets  }}
{{- if $ips }}
      imagePullSecrets:
{{ toYaml $ips | indent 6 }}
{{- end }}
{{- end }}

{{- with .Values.dbmigration.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
{{- end }}
{{- end }}
