{{- if and .Values.auditlogs.enabled .Values.global.enterprise }}
{{- $context := (dict "dot" . "component" "auditlogs") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mender.fullname" . }}-auditlogs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mender.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "mender.fullname" . }}-auditlogs
    app.kubernetes.io/component: auditlogs
spec:
  {{- if not (or .Values.auditlogs.hpa .Values.default.hpa ) }}
  replicas: {{ .Values.auditlogs.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mender.fullname" . }}-auditlogs

  # if deployment is not completed within 10 min, consider it failed,
  # as result deployment Reason=ProgressDeadlineExceeded
  # needs to be big enough to rollout to complete
  progressDeadlineSeconds: 600

  # Rollout upgrade one by one
  # In this case we warranty there are always instances online.
  # In case any issues, they will be detected early and deployment be stopped.
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    {{- include "mender.auditlogsPodTemplate" $context | nindent 4 }}

{{- end }}
